version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: market-research
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: