version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask-vue-server
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: market-research
    ports:
      - "5432:5432"

